"""empty message

Revision ID: 6f40e7221cc5
Revises: 
Create Date: 2023-03-06 01:03:41.143118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f40e7221cc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_color',
    sa.Column('color_name', sa.Enum('YELLOW', 'BLUE', 'GRAY', name='carcolorsenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_type',
    sa.Column('type_car_name', sa.Enum('HATCH', 'SEDAN', 'CONVERTIBLE', name='cartypeenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('name', sa.String(length=155), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('car_name', sa.String(length=155), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=False),
    sa.Column('type_car_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['car_color.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_car_id'], ['car_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('person')
    op.drop_table('car_type')
    op.drop_table('car_color')
    # ### end Alembic commands ###
